[package]
name = "redon-tech/redon-ui"
version = "0.1.0-alpha.1"
license = "MIT"
authors = ["parker02311"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.3.0"
ui-labs = "pepeeltoro41/ui-labs@2.3.0"
