[package]
name = "redon-tech/redon-ui"
description = "RedonUI is a component library for Fusion using the catppuccin color pallet. Read more at the project homepage!"
version = "0.1.0-alpha.9"
license = "MIT"
authors = ["parker02311"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "wally.lock", "LICENSE.md"]

[dependencies]
Fusion = "elttob/fusion@0.3.0"
ui-labs = "pepeeltoro41/ui-labs@2.3.0"
