name: Build Standalone

on:
    release:
        types: [published]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Aftman
              uses: ok-nick/setup-aftman@v0.4.2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Dependencies
              run: wally install

            - name: Build
              run: rojo build -o RedonUI.rbxmx standalone.project.json

            - name: Upload Files
              run: gh release upload ${{ github.ref_name }} RedonUI.rbxmx
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}